// 🤖 PAIMANA Gemini AI Service
// Direct Real-Time Integration with Google Gemini LLM API + Injected Knowledge Grounding

import { 
  DETAILED_PROJECTS, 
  PAIMANA_SUMMARY, 
  ESCALATION_DRIVERS, 
  NORTH_EAST_SUMMARY, 
  STATES_SUMMARY 
} from '../data/paimanaData';
import { TENDERS_DATA } from '../data/tendersData';

// Default Gemini API Key (Loaded securely from environment or UI input)
export const DEFAULT_GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY || "AQ.Ab8RN6IlduK_iAfNlxyKc6PnU0jzlpvq_TDZxGbvGK-5exHc6g";

/**
 * Builds compact, highly-structured context representing the entire PAIMANA ecosystem.
 */
function buildKnowledgePrompt() {
  const tendersContext = TENDERS_DATA.map(t => ({
    id: t.id,
    title: t.title,
    agency: t.agency,
    ministry: t.ministry,
    sector: t.sector,
    state: t.state,
    status: t.status, // ongoing, upcoming, completed
    estimatedCostCr: t.estimatedCostCr,
    emdAmountCr: t.emdAmountCr,
    bidClosingDate: t.bidClosingDate,
    preBidMeetingDate: t.preBidMeetingDate,
    expectedBidOpening: t.expectedBidOpening,
    awardedContractor: t.awardedContractor,
    awardedCostCr: t.awardedCostCr,
    mandatoryRequirements: t.mandatoryRequirements,
    biddersDebrief: t.biddersDebrief
  }));

  const projectsContext = DETAILED_PROJECTS.map(p => ({
    id: p.id,
    name: p.name,
    agency: p.agency,
    ministry: p.ministry,
    sector: p.sector,
    state: p.state,
    originalCostCr: p.originalCostCr,
    revisedCostCr: p.revisedCostCr,
    expenditureCr: p.expenditureCr,
    physicalProgress: p.physicalProgress,
    financialProgress: p.financialProgress,
    delayMonths: p.delayMonths,
    riskLevel: p.riskLevel,
    riskScore: p.riskScore,
    aiDiagnosis: p.aiDiagnosis,
    aiPrescription: p.aiPrescription
  }));

  return `You are PAI AI, the official intelligent copilot for PAIMANA (Ministry of Statistics and Programme Implementation - MoSPI / IPMD).
You have real-time access to the official 486th Flash Report dataset and the Central Public Procurement Portal (CPPP) E-Tenders Registry.

### KNOWLEDGE BASE DATASET:
1. Macro Flash Report:
- Total Monitored Projects: 1,981 projects (₹150 Cr+ threshold) across 17 ministries.
- Original Baseline Outlay: ₹37.13 Lakh Cr (₹37,12,662 Cr).
- Revised Outlay: ₹42.78 Lakh Cr (+₹5.65 Lakh Cr / +15.24% cost overrun).
- Cumulative Disbursals: ₹20.36 Lakh Cr (47.59%).
- 23 projects at Critical Risk, 47 projects at High Risk, 86 Medium Risk, 124 Low Risk.

2. Central Sector E-Tenders:
${JSON.stringify(tendersContext, null, 2)}

3. Monitored Infrastructure Projects:
${JSON.stringify(projectsContext, null, 2)}

4. Top Escalation Drivers (Pareto):
- Land Acquisition Disputes: 34.2% share (₹1,93,480 Cr impact, avg delay +28.4 mo)
- Forest & Environmental Clearances Stage-I/II: 22.8% share (₹1,28,988 Cr impact, avg delay +22.1 mo)
- Contractor Default & Cash-flow Strains: 18.5% share (₹1,04,661 Cr impact, avg delay +19.5 mo)
- Scope Changes & DPR Inadequacy: 14.1% share (₹79,769 Cr impact)
- Law & Order, Encroachments: 10.4% share (₹58,836 Cr impact)

### INSTRUCTIONS:
- Answer the user's question directly, accurately, and with specific data from the knowledge base.
- If asked for specific filters (e.g. budget under ₹1000 Cr, specific status like 'upcoming', 'ongoing', specific sector, or specific state), strictly filter and return ONLY the matching items. Do NOT dump all tenders.
- Use clean formatting with clear headings (### Header, #### Subheader), bullet points (* Item), and bold text (**Bold**).
- Be polite, executive, and concise.`;
}

/**
 * Executes a live query with Gemini LLM API
 */
export async function queryGeminiApi(userQuery, customApiKey) {
  const apiKey = customApiKey || DEFAULT_GEMINI_API_KEY;
  const systemContext = buildKnowledgePrompt();

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

  const payload = {
    contents: [
      {
        role: "user",
        parts: [
          {
            text: `${systemContext}\n\nUser Question: "${userQuery}"\n\nProvide an accurate, well-structured, and concise response:`
          }
        ]
      }
    ],
    generationConfig: {
      temperature: 0.15,
      maxOutputTokens: 1500
    }
  };

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(`Gemini API Error (${response.status}): ${errorData.error?.message || response.statusText}`);
  }

  const data = await response.json();
  const candidate = data.candidates?.[0];
  const replyText = candidate?.content?.parts?.[0]?.text;

  if (!replyText) {
    throw new Error("No text generated by Gemini model");
  }

  return replyText;
}

/**
 * Ultra-Smart Deterministic Fallback Engine
 * Handles exact numerical, filter, and logical reasoning if API key is rate-limited or offline.
 */
export function querySmartLocalEngine(query) {
  const rawQ = query.trim();
  const q = rawQ.toLowerCase();

  // -------------------------------------------------------------
  // 1. TENDER QUERIES WITH BUDGET & STATUS FILTERS (e.g. "upcoming tenders requiring budget under 1000 cr")
  // -------------------------------------------------------------
  if (q.includes("tender") || q.includes("bid") || q.includes("procurement") || q.includes("rfp")) {
    
    // Determine status filter
    let targetStatus = null;
    if (q.includes("upcoming") || q.includes("future") || q.includes("pipeline") || q.includes("draft")) {
      targetStatus = "upcoming";
    } else if (q.includes("ongoing") || q.includes("active") || q.includes("open") || q.includes("live")) {
      targetStatus = "ongoing";
    } else if (q.includes("completed") || q.includes("awarded") || q.includes("won")) {
      targetStatus = "completed";
    }

    // Determine budget filter (under 1000, less than 500, above 2000, etc.)
    let maxBudget = null;
    let minBudget = null;

    const underMatch = q.match(/(?:under|below|less than|within|max|<|<=)\s*(?:₹|rs\.?)?\s*(\d+(?:\.\d+)?)\s*(?:cr|crore)?/i);
    if (underMatch) {
      maxBudget = parseFloat(underMatch[1]);
    }

    const aboveMatch = q.match(/(?:above|greater than|more than|exceeding|>|>=)\s*(?:₹|rs\.?)?\s*(\d+(?:\.\d+)?)\s*(?:cr|crore)?/i);
    if (aboveMatch) {
      minBudget = parseFloat(aboveMatch[1]);
    }

    // Filter tenders accurately
    let filteredTenders = TENDERS_DATA.filter(t => {
      if (targetStatus && t.status !== targetStatus) return false;
      if (maxBudget !== null && t.estimatedCostCr > maxBudget) return false;
      if (minBudget !== null && t.estimatedCostCr < minBudget) return false;
      return true;
    });

    if (filteredTenders.length > 0) {
      const statusTitle = targetStatus === 'upcoming' 
        ? 'Upcoming Tenders & Pipeline RFPs' 
        : targetStatus === 'ongoing' 
          ? 'Active Ongoing Tenders (Open for Bidding)' 
          : targetStatus === 'completed'
            ? 'Awarded & Completed Tenders'
            : 'Central Sector Tenders';

      const budgetTitle = maxBudget !== null 
        ? `with Estimated Budget Under ₹${maxBudget.toLocaleString()} Cr`
        : minBudget !== null
          ? `with Estimated Budget Above ₹${minBudget.toLocaleString()} Cr`
          : '';

      let text = `### 📋 ${statusTitle} ${budgetTitle}\n\n`;
      text += `Found **${filteredTenders.length} matching tender package${filteredTenders.length > 1 ? 's' : ''}** in the PAIMANA E-Procurement database:\n\n`;

      filteredTenders.forEach((t, idx) => {
        text += `#### ${idx + 1}. ${t.title}\n`;
        text += `* **Tender ID:** \`${t.id}\` | **Issuing Agency:** **${t.agency}** (${t.ministry})\n`;
        text += `* **Estimated Value:** **₹${t.estimatedCostCr.toLocaleString()} Crore** | **EMD Amount:** ₹${t.emdAmountCr} Cr\n`;
        text += `* **Location:** 📍 ${t.location} (${t.sector})\n`;
        text += `* **Procurement Method:** ${t.procurementType} • ${t.evaluationMethod}\n`;
        
        if (t.status === 'upcoming') {
          text += `* **📅 Pre-Bid Conference Date:** **${t.preBidMeetingDate}**\n`;
          text += `* **🚀 Expected Bid Launch:** **${t.expectedBidOpening}**\n`;
        } else if (t.status === 'ongoing') {
          text += `* **⏳ Bid Closing Deadline:** **${t.bidClosingDate.replace('T', ' at ')} IST**\n`;
          text += `* **🔓 Technical Bid Opening:** **${t.bidOpeningDate}**\n`;
        } else if (t.status === 'completed') {
          text += `* **🏆 Awarded To:** **${t.awardedContractor}** for ₹${t.awardedCostCr} Cr on ${t.awardDate}\n`;
        }

        if (t.mandatoryRequirements) {
          text += `* **Mandatory Criteria:** Min Turnover ₹${t.mandatoryRequirements.minAnnualTurnoverCr} Cr | Solvency ₹${t.mandatoryRequirements.financialSolvencyCr} Cr\n`;
        }
        text += `\n`;
      });

      // If other upcoming tenders were excluded because they exceeded the budget
      if (targetStatus === 'upcoming' && maxBudget !== null) {
        const otherUpcoming = TENDERS_DATA.filter(t => t.status === 'upcoming' && t.estimatedCostCr > maxBudget);
        if (otherUpcoming.length > 0) {
          text += `#### ℹ️ Other Upcoming Pipeline Packages (Above ₹${maxBudget} Cr):\n`;
          otherUpcoming.forEach(ot => {
            text += `* **${ot.id} (${ot.agency}):** ${ot.title} — **₹${ot.estimatedCostCr.toLocaleString()} Cr** (Pre-Bid: ${ot.preBidMeetingDate})\n`;
          });
        }
      }

      return text;
    } else {
      return `### 📋 No Matching Tenders Found

No tenders currently match your exact criteria (**Status:** \`${targetStatus || 'Any'}\`, **Budget limit:** \`${maxBudget ? `< ₹${maxBudget} Cr` : minBudget ? `> ₹${minBudget} Cr` : 'Any'}\`).

**Available Tender Packages in System:**
* **₹680 Cr** — IGGL North East Gas Grid Pipeline (Ongoing)
* **₹920 Cr** — Coal India Rapid Loading Silos (Upcoming)
* **₹1,400 Cr** — AAI Greenfield Airport Terminal (Upcoming)
* **₹1,850 Cr** — NHAI Vadodara-Mumbai Expressway (Ongoing)
* **₹2,420 Cr** — RVNL Rishikesh-Karanprayag Tunnel (Ongoing)
* **₹3,150 Cr** — NHSRCL High Speed Track Slabs (Upcoming)
* **₹5,100 Cr** — NTPC Supercritical Thermal BoP (Ongoing)`;
    }
  }

  // -------------------------------------------------------------
  // 2. HIGH-RISK / CRITICAL RISK PROJECTS
  // -------------------------------------------------------------
  if (q.includes("risk") || q.includes("critical") || q.includes("stalled") || q.includes("delayed") || (q.includes("in progress") && q.includes("high"))) {
    const criticalProjects = DETAILED_PROJECTS.filter(p => p.riskLevel === 'Critical' || p.riskLevel === 'High');
    let text = `### 🚨 In-Progress Projects Classified at High / Critical Risk\n\n`;
    text += `According to the **486th Flash Report (MoSPI / IPMD)**, **23 projects are at Critical Risk** and **47 projects are at High Risk**:\n\n`;

    criticalProjects.forEach((p, idx) => {
      text += `#### ${idx + 1}. ${p.name}\n`;
      text += `* **Project ID:** \`${p.id}\` | **Agency:** **${p.agency}** (${p.ministry})\n`;
      text += `* **Risk Rating:** **🔴 ${p.riskLevel.toUpperCase()} RISK (Score: ${p.riskScore}/100)**\n`;
      text += `* **Cost Profile:** Original: ₹${p.originalCostCr.toLocaleString()} Cr ➔ Revised: **₹${p.revisedCostCr.toLocaleString()} Cr** (+${(((p.revisedCostCr - p.originalCostCr)/p.originalCostCr)*100).toFixed(1)}%)\n`;
      text += `* **Progress:** Physical: **${p.physicalProgress}%** | Financial Burn: **${p.financialProgress}%** | Delay: **+${p.delayMonths} Months**\n`;
      if (p.aiDiagnosis) text += `* **⚠️ AI Risk Diagnosis:** *"${p.aiDiagnosis}"*\n`;
      if (p.aiPrescription) text += `* **💡 AI Recommended Action:** *"${p.aiPrescription}"*\n`;
      text += `\n`;
    });
    return text;
  }

  // -------------------------------------------------------------
  // 3. CONVERSATIONAL GREETINGS
  // -------------------------------------------------------------
  const greetings = ['hi', 'hello', 'hey', 'namaste', 'good morning', 'good afternoon', 'good evening'];
  if (greetings.some(g => q === g || q.startsWith(g + ' '))) {
    return `### 👋 Hello! Welcome to PAI AI Copilot
I am your intelligent assistant for **National Infrastructure Intelligence & Central E-Procurement** (MoSPI 486th Flash Report & CPPP Tenders).

**Here are some immediate questions you can ask me:**
* 🚨 *"What are the upcoming tenders requiring budget under 1000 cr?"*
* 🛣️ *"Show me currently in-progress projects that are highly in risk"*
* 🔍 *"Why was Infracon disqualified from the DFCCIL tender?"*
* 🗺️ *"What is the total capital outlay in Maharashtra vs Uttar Pradesh?"*`;
  }

  // -------------------------------------------------------------
  // 4. GENERAL FALLBACK
  // -------------------------------------------------------------
  return `### 💡 PAI AI Synthesis for: "${rawQ}"

* **Portfolio Status:** 1,981 central sector projects (costing ₹150 Cr+) are actively tracked under the **486th Flash Report (April 2026)**.
* **Key Risk Segments:** 23 projects are currently at **Critical Risk**, while 47 are at **High Risk**.
* **Tenders Intelligence:** 4 active tenders are open with bid submission closing in **May and June 2026**.

**Suggested questions you can ask me:**
1. *"What are the upcoming tenders requiring budget under 1000 cr?"*
2. *"Show me currently in-progress projects that are highly in risk"*
3. *"Why was Infracon disqualified from the DFCCIL tender?"*
4. *"What is the capital outlay in Maharashtra vs Uttar Pradesh?"*`;
}
